mod any;
mod primitive;
mod string;

pub use self::any::{Any, Object};
pub use self::primitive::{Bool, Double, Float, Int, Long};
pub use self::string::StrValue;

/// Sequence of elements of type T.
pub type List<T> = std::boxed::Box<[T]>;

/// This trait is implemented for all types generated by "schema_salad".<br>
/// Serves as a marker trait to identify types that belong to this crate.
// XXX: Mirrors the "std::any::Any" type methods
pub trait SaladType: 'static {
    #[doc(hidden)]
    fn type_id(&self) -> std::any::TypeId {
        std::any::TypeId::of::<Self>()
    }
}

// XXX: Mirrors the "std::any::Any" type methods
impl dyn SaladType {
    /// Checks whether the concrete type and the given type
    /// match.
    #[inline]
    pub fn is<T: SaladType>(&self) -> bool {
        let self_typeid = SaladType::type_id(self);
        let given_typeid = std::any::TypeId::of::<T>();

        self_typeid == given_typeid
    }

    /// Downcasts a reference to the trait object to a concrete
    /// type if the types match.
    #[inline]
    pub fn downcast_ref<T: SaladType>(&self) -> Option<&T> {
        // SAFETY: just checked whether we are pointing to the correct type, and we can rely on
        // that check for memory safety because we have implemented SaladType for all types; no other
        // impls can exist as they would conflict with our impl.
        if self.is::<T>() {
            Some(self.downcast_ref_unchecked())
        } else {
            None
        }
    }

    /// Downcasts a reference to the trait object to a concrete
    /// type without check if the types match.
    #[inline]
    pub fn downcast_ref_unchecked<T: SaladType>(&self) -> &T {
        debug_assert!(self.is::<T>());
        unsafe { &*(self as *const dyn SaladType as *const T) }
    }
}
