mod any;
mod error;
pub mod primitive;
mod util;

pub use self::{
    any::{SaladAny, SaladObject},
    error::SaladTypeDowncastError,
};

/// This trait serves as a marker trait for all Rust types that
/// are generated by `schema_salad`.
pub trait SaladType {}
